### ISSUE TITLE
Error: Not Found - https://docs.github.com/rest

### ISSUE THREAD

**Issue by jdouitsis** [juliangruber/approve-pull-request-action#77]
Hello, 

I ran this GH action like so

```
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.synchronize.outputs.pull_request_number }}
          repo: jdouitsis/crowdinTest
```

And this is the output I got

```
Run juliangruber/approve-pull-request-action@v2
  with:
    github-token: ***
    repo: jdouitsis/crowdinTest
  
Error: Not Found - https://docs.github.com/rest
```

Any advice would be greatly appreciated! 

**EDIT: Nov 8, 2024**
The repository in question `jdouitsis/crowdinTest` is a private repository

✅ **Solution** ✅
Turns out there was a lag between the PR being created and the the step for approving it. So once I put in a 5 second delay between PR creation and approval, everything worked out well. Also had to have a different `GITHUB_TOKEN` for creating and approving said PR
